proxy: socks5://127.0.0.1:7890

hosts:
  - https://raw.hellogithub.com/hosts

rules:
  - if: xyz in domain
    then: pass

  - if: domain ends with .cn
    then: pass

middlewares:
  - rules
  - cache
  - hosts
  - block
 