#proxy: socks5://127.0.0.1:7890
timeout: 5

stats:
  max_size: 200

hosts:
  - hosts
  - https://raw.hellogithub.com/hosts

middlewares:
  - cache
  - hosts

upstreams:
  - name: 114dns
    host: 114.114.114.114
    priority: 11

  - name: baidu
    host: 180.76.76.76

  - name: alidns-https
    url: https://dns.alidns.com/dns-query
    priority: 10

  - name: alidns-tls
    host: dns.alidns.com
    type: tls
    priority: 0

  - name: google-https
    url: https://dns.google/dns-query
  
  - name: cloudflare-https
    url: https://1.1.1.1/dns-query
    disable: true
    
  - name: google-tls
    type: tls
    host: 8.8.8.8

  - name: cloudflare
    host: 1.1.1.1
    disable: true

  - name: cloudflare-tls
    type: tls
    host: 1.1.1.1
    disable: true
