hosts:
  - !path hosts
  - https://raw.hellogithub.com/hosts

block:
  - !path block.txt

http:
  root: !path ../public

rules:
  - !include cn-domain.yml

middlewares:
  - rules
  - hosts
  - block
  - cache
  - log
